name: Check PR Title

on:
  pull_request:
    branches: ['master']
    types: ['opened', 'reopened', 'edited', 'synchronize']

permissions:
  contents: read

jobs:
  check_pr_title:
    name: Check PR title
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Check PR title
        uses: rudderlabs/github-action-check-pr-title@e5718471c8eebd75c51a10ccce35f2cf33d18c04 # v1.0.12
